version: '3.9'

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    command:
#      - "--memory.max-traces=1000"
      - "--collector.grpc-server.host-port=jaeger-collector:14250"
    environment:
      - SPAN_STORAGE_TYPE=memory
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "14269:14269" # CollectorAdminHTTP
      - "14268:14268" # CollectorHTTP
      - "14250:14250" # CollectorGRPC
  jaeger-agent:
    image: jaegertracing/jaeger-agent:latest
    user: root
    command:
#      - "--reporter.grpc.host-port=jaeger-collector:14250"
      - "--reporter.grpc.host-port=host.docker.internal:14250"
      - "--reporter.grpc.tls.enabled=false"
      - "--reporter.grpc.retry.max=1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5775:5775/udp" #AgentZipkinThriftCompactUDP - не надо
      - "6831:6831/udp" #AgentJaegerThriftCompactUDP
      - "6832:6832/udp" #AgentJaegerThriftBinaryUDP
      - "5778:5778" #AgentConfigServerHTTP
      - "14271:14271" # AgentAdminHTTP is the default admin HTTP port (health check, metrics, etc.)
    environment:
      - SPAN_STORAGE_TYPE=memory
#  jaeger-query:
#    image: jaegertracing/jaeger-query:latest
##    command: ["--memory.max-traces=1000"]
#    environment:
#      - SPAN_STORAGE_TYPE=memory
#    ports:
#      - "16686:16686"
#      - "16687:16687" #HealthCheck
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080:8080"
    command: [ "all" ]
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger-agent:5778/sampling
    depends_on:
      - jaeger-agent
      - jaeger-collector