kind: ConfigMap
apiVersion: v1
metadata:
  name: otel-config-map
data:
  collector_gateway: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      tail_sampling:
        decision_wait: 5s
        num_traces: 1000
        expected_new_traces_per_sec: 1000
        policies:
          [
            {
              name: bad-traces,
              type: status_code,
              status_code: { status_codes: [ ERROR ] }
            },
            {
              name: and-policy-1,
              type: and,
              and: {
                and_sub_policy:
                  [
                    {
                      name: all-traces-OK,
                      type: status_code,
                      status_code: { status_codes: [ OK ] },
                    },
                    {
                      name: all-traces-1,
                      type: probabilistic,
                      probabilistic: { sampling_percentage: 1 }
                    },
                  ]
              }
            },
          ]


    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: "http://service-tempo.esavelyev:4317"
        tls:
          insecure: true
    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          #processors: [tail_sampling]
          exporters: [otlp, logging]
  other_server_block.conf: |
    ######### OTHER SERVER #######....