apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esavelyev

resources:
  #- ../k8s/base/deployment_jaeger.yml
  - ../k8s/base/deployment_tempo.yml
  - ../k8s/base/deployment_grafana.yml
  - ../k8s/base/deployment_otel.yml
  #- ../k8s/base/service_jaeger.yml
  - ../k8s/base/service_tempo.yml
  - ../k8s/base/service_grafana.yml
  - ../k8s/base/otel_config.yml
  - ../k8s/base/grafana_config.yml
  - ../k8s/base/tempo_config.yml
  - ../k8s/base/service_otel.yml
  - ../k8s/base/ingress_grafana.yml
