apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esavelyev

resources:
  - ../k8s/base/deployment_jaeger.yml
  - ../k8s/base/deployment_otel.yml
  - ../k8s/base/service_jaeger.yml
  - ../k8s/base/otel_config.yml
  - ../k8s/base/service_otel.yml
