version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.73.0
    container_name: jaeger-all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
    ports:
      # UI и API порты
      - "16686:16686"    # Web UI
      - "16685:16685"    # GRPC API
      # OTLP порты
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
      # Jaeger порты
      - "6831:6831/udp"  # Jaeger compact thrift (UDP)
      - "6832:6832/udp"  # Jaeger binary thrift (UDP)
      - "5778:5778"      # Config HTTP
      - "14268:14268"    # Jaeger thrift HTTP
      - "14250:14250"    # Jaeger model.proto